CONTENT_STORE_HEADER = {'base_path': object,
                        'content_id': object,
                        'title': object,
                        'description': object,
                        'publishing_app': object,
                        'document_type': object,
                        'details': object,
                        'text': object,
                        'organisations': object,
                        'taxons': object,
                        'step_by_steps': object,
                        'details_parts': object,
                        'first_published_at': object,
                        'public_updated_at': object,
                        'updated_at': object,
                        'finder': object,
                        'facet_values': object,
                        'facet_groups': object,
                        'has_brexit_no_deal_notice': bool,
                        'withdrawn': bool,
                        'withdrawn_at': object,
                        'withdrawn_explanation': object}

CONTENT_STORE_DATE = ['first_published_at',
                      'public_updated_at',
                      'updated_at',
                      'withdrawn_at']

# from: https://www.gov.uk/guidance/how-to-publish-on-gov-uk/creating-and-updating-pages
ATTACHMENTS = [".chm",
               ".csv",
               ".diff",
               ".doc",
               ".docx",
               ".dot",
               ".dxf",
               ".eps",
               ".gif",
               ".gml",
               ".ics",
               ".jpg",
               ".kml",
               ".odp",
               ".ods",
               ".odt",
               ".pdf",
               ".png",
               ".ppt",
               ".pptx",
               ".ps",
               ".rdf",
               ".ris",
               ".rtf",
               ".sch",
               ".txt",
               ".vcf",
               ".wsdl",
               ".xls",
               ".xlsm",
               ".xlsx",
               ".xlt",
               ".xml",
               ".xsd",
               ".xslt",
               ".zip"]
